### PR TITLE
Retry connection to aws after exception

### PR DESCRIPTION
**Pull request by TechHummel**

### CODE REVIEW

**Comment by TechHummel** [comment]
@elektrolitr Would you be able to use the version from this branch and check if this fixes the issue?

**Comment by elektrolitr** [comment]
@TechHummel  sure, I can test this 

However, the issue didn't occur since the original message, so I'm not sure how complete and representative my testing will be

**Comment by TechHummel** [comment]
Then I don't think there is a point, to be honest 😄 
Should we close the issue then?

**Comment by elektrolitr** [comment]
@TechHummel I think yes, as I can't recreate the issue

**Comment by TechHummel** [comment]
@rowysock I would like to have this MR merged, please.
More resilience won't hurt – even if it doesn't directly fix the linked issues.

**Review by rowysock — APPROVED** [review]

**Comment by rowysock** [comment]
Fully agree. Thank you for this change and sorry for the long wait time.

Do you want to release a new version soon?

**Comment by TechHummel** [comment]
Don't worry - I was quite busy too,.
I'd like to fix #119 and #131 before a new release - what do you think?

**Pull request merged**
