### PR TITLE
Fix translations

### LINKED ISSUE #119: Device states again not translated after HA core update
Hey
Again my device states and options are strings not translated, happened after HA update.
Shows now for instance
DEVICE_STATE_OFF instead nice Off like it was before.

### PR DESCRIPTION
**Pull request by TechHummel**
Closes #119 

I am unable to verify if translations are working for all devices and languages. I can only verify that translations are working now for washing machines in German language.
Since translation_keys are now used, entities will have a different (localized) name when the HomeWhiz device is removed and added again to / from Homeassistant.

The generate_translations script now uses a Python module which uses Google translate to translate entities for which the HomeWhiz API does not provide translations.

### CODE REVIEW

**Comment by TechHummel** [comment]
Working now, although there are some inconsistencies:
image

We could start adding extra rules for translations - this would be something for later though.

@rowysock Could you approve this PR and merge? I am undecided about whether we should squash commits 🤔 
We could then maybe release a 0.5.0 or a beta version?

**Comment by elektrolitr** [comment]
Hi!

I've checked with my setup (the appliance is dishwasher and the language is English)

Some of entities are translated, however, there are some either not translated or translated in a way that I think may be error

There are two selects with the same name displayed:
Displayed name: Dishwasher
one is **select.dishwasher** and it actually a program name 
another one is **select.dishwasher_2** and it represents a Detergent Dose

image

The program names itself are not translated in both _select_ and _sensor_: 
image

**Comment by TechHummel** [comment]
Thanks for the feedback, very appreciated! 👍 

Did you remove the device and add it again before testing or did you just upgrade?

I added an extra log entry which reports translation keys - could you check which translation keys are missing in the json translation files? Alternatively, you could share you logs! 😄

**Comment by elektrolitr** [comment]
> 

I've removed the device and added again, sure. Before that there were no changes in translation

I've also checked the logs and these are empty. But I've restarted HA several times after addition of "new" device. Is the activity logged only on addition of devices? I can try to re-add once again if it helps

**Comment by TechHummel** [comment]
I'm unsure about when logging is triggered but I think you might be correct with your assumption. The information are logged with level debug, as usual.

**Comment by elektrolitr** [comment]
There's some logs after restart of HA
What's interesting is that every "Retrieving translation_key" repeats 3 times

<details>
<summary>The log </summary>
`2023-07-10 11:50:59.422 INFO (MainThread) [custom_components.homewhiz] Setting up entry F999931386498761371494
2023-07-10 11:50:59.423 INFO (MainThread) [custom_components.homewhiz] Setting up cloud connection
2023-07-10 11:50:59.476 DEBUG (MainThread) [custom_components.homewhiz] Sensors: ['state', 'dishwasher_program', 'sub_state', 'dishwasher_delay', 'dishwasher_duration', 'dishwasher_remaining', 'setting_detergent_type', 'dishwasher_rinse_aid_level', 'dishwasher_liquid_detergent_level', 'dishwasher_water_hardness']
2023-07-10 11:50:59.479 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key state
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key state
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key state
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_program
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_program
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_program
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key sub_state
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key sub_state
2023-07-10 11:50:59.480 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key sub_state
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_delay
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_delay
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_delay
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_duration
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_duration
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_duration
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_remaining
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_remaining
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_remaining
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_detergent_type
2023-07-10 11:50:59.481 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_detergent_type
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_detergent_type
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_rinse_aid_level
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_rinse_aid_level
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_rinse_aid_level
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_level
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_level
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_level
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_water_hardness
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_water_hardness
2023-07-10 11:50:59.482 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_water_hardness
2023-07-10 11:50:59.522 DEBUG (MainThread) [custom_components.homewhiz] Binary sensors: ['remote_control', 'dishwasher_warning_no_rinse_aid', 'dishwasher_warning_no_salt', 'dishwasher_warning_no_water', 'dishwasher_warning_check_the_filter', 'dishwasher_warning_door_is_open', 'dishwasher_warning_call_service', 'dishwasher_liquid_detergent_low']
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key remote_control
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key remote_control
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key remote_control
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_rinse_aid
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_rinse_aid
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_rinse_aid
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_salt
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_salt
2023-07-10 11:50:59.525 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_salt
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_water
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_water
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_no_water
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_check_the_filter
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_check_the_filter
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_check_the_filter
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_door_is_open
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_door_is_open
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_door_is_open
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_call_service
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_call_service
2023-07-10 11:50:59.526 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_warning_call_service
2023-07-10 11:50:59.527 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_low
2023-07-10 11:50:59.527 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_low
2023-07-10 11:50:59.527 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_low
2023-07-10 11:50:59.549 DEBUG (MainThread) [custom_components.homewhiz] Selects: ['state', 'dishwasher_program', 'setting_detergent_type', 'dishwasher_rinse_aid_level', 'dishwasher_liquid_detergent_level', 'dishwasher_water_hardness']
2023-07-10 11:50:59.556 DEBUG (MainThread) [custom_components.homewhiz] ACs: []
2023-07-10 11:50:59.560 DEBUG (MainThread) [custom_components.homewhiz] Switches: ['dishwasher_hygiene_intense', 'dishwasher_steamgloss', 'dishwasher_deepwash', 'dishwasher_fastplus', 'dishwasher_halfload', 'setting_auto_door', 'setting_inner_illumination']
2023-07-10 11:50:59.560 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key state
2023-07-10 11:50:59.560 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key state
2023-07-10 11:50:59.560 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key state
2023-07-10 11:50:59.560 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_program
2023-07-10 11:50:59.560 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_program
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_program
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_detergent_type
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_detergent_type
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_detergent_type
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_rinse_aid_level
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_rinse_aid_level
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_rinse_aid_level
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_level
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_level
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_liquid_detergent_level
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_water_hardness
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_water_hardness
2023-07-10 11:50:59.561 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_water_hardness
2023-07-10 11:50:59.568 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_hygiene_intense
2023-07-10 11:50:59.568 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_hygiene_intense
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_hygiene_intense
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_steamgloss
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_steamgloss
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_steamgloss
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_deepwash
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_deepwash
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_deepwash
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_fastplus
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_fastplus
2023-07-10 11:50:59.569 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_fastplus
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_halfload
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_halfload
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key dishwasher_halfload
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_auto_door
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_auto_door
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_auto_door
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_inner_illumination
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_inner_illumination
2023-07-10 11:50:59.570 DEBUG (MainThread) [custom_components.homewhiz] Retrieving translation_key setting_inner_illumination`
</details>

If I re-add the appliance, 3 more requests are logged on top and the rest is the same:

```
2023-07-10 12:06:45.036 DEBUG (MainThread) [custom_components.homewhiz] Actual canonical request: 
GET\n/my-homes\n\nhost:smarthome.arcelikiot.com\nx-amz-date:20230710T090645Z\nx-amz-security-token: ....
2023-07-10 12:06:45.319 DEBUG (MainThread) [custom_components.homewhiz] Actual canonical request: 
GET\n/my-homes/731966\n\nhost:smarthome.arcelikiot.com\nx-amz-date:20230710T090645Z\nx-amz-security-token: ....
2023-07-10 12:06:46.857 DEBUG (MainThread) [custom_components.homewhiz] Actual canonical request: 
GET\n/procam/contents\napplianceId=F999931386498761371494&ctype=CONFIGURATION%2CLOCALIZATION&lang=en-GB&testMode=true\nhost:api.arcelikiot.com\nx-amz-date:20230710T090646Z\nx-amz-security-token: ....

```

There are YAMLs from DevTools: 

```
select.dishwasher

options:
  - program_auto
  - program_aqua_flex
  - program_intensive_70
  - program_eco_50
  - program_delicate
  - program_quick_and_shine
  - program_mini
  - program_prewash
  - program_quiet
  - program_clean_and_shine
  - program_innerclean
device_class: homewhiz__dishwasher_program
friendly_name: Dishwasher
```

```
select.dishwasher_2

options:
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
device_class: homewhiz__dishwasher_liquid_detergent_level
friendly_name: Dishwasher

```

**Comment by TechHummel** [comment]
@elektrolitr I added your device ID to the script which generates the translations. Looking at the changes, I would expect it to work fine now!

**Comment by elektrolitr** [comment]
@TechHummel  your expectations are right, the translations are spot on now!

**Comment by TechHummel** [comment]
Thanks for the feedback!
I do wonder whether the HomeWhiz API only offers translations for markets where speific devices are sold.
E.g., only certain options for dishwasher program are translated into German. We could utilize the translations module to translate those options too – but this would be something for a future version.
image

Anyway, I'd propose to merge this and release a new version. Missing translations can then be added afterwards + it is always possible to select older versions of the plugin in case translations are missing.

**Review by rowysock — APPROVED** [review]
Great work with fixing the translation. I see it wasn't an easy fix

**Comment by TechHummel** [comment]
@rowysock Yes,  I think this would be a good opportunity. Thank you 👍

**Pull request merged**
