### PR TITLE
Add github actions for validation

### PR DESCRIPTION
**Pull request by TechHummel**
This is [required for repositories](https://hacs.xyz/docs/publish/include/#before-submitting) in order to be added to the HACS default list.

### CODE REVIEW

**Comment by TechHummel** [comment]
This is the summary of errors:

```
Error:  <Validation topics> failed:  The repository has no valid topics (More info: https://hacs.xyz/docs/publish/include#check-repository )
Error:  <Validation description> failed:  The repository has no description (More info: https://hacs.xyz/docs/publish/include#check-repository )
```
These should be easy to fix

```
Error:  <Validation brands> failed:  The repository has not been added as a custom domain to the brands repo (More info: https://hacs.xyz/docs/publish/include#check-brands )
```
This is ongoing: https://github.com/home-assistant/brands/pull/3655

```
Error:  <Validation hacsjson> failed:  extra keys not allowed @ data['domains'] (More info: https://hacs.xyz/docs/publish/include#check-hacs-manifest )
```

```
Error: R] [DEPENDENCIES] Using component bluetooth but it's not in 'dependencies' or 'after_dependencies'
Error: R] [MANIFEST] Domain is missing an IoT Class
Error: R] [TRANSLATIONS] Invalid strings.json: required key not provided @ data['options']['step']. Got None
Error: R] [TRANSLATIONS] Invalid translations/en.json: required key not provided @ data['options']['step']. Got None
```

This should all be fixable with small adjustments.

**Comment by TechHummel** [comment]
I'm just wondering: Can we remove the `options` key from the translations and strings.yaml? The integration does not offer configuration anyway, right?

**Comment by TechHummel** [comment]
Now we just have to wait for the logos to be added to the brands repository, then we can add the integration to HACS 😄

**Review by rowysock — APPROVED** [review]
Looks great!

**Pull request merged**
