### PR TITLE
Add more logging

### PR DESCRIPTION
**Pull request by TechHummel**
This will add some more logging commands to help identify unknown states.

### CODE REVIEW

**Comment by StarvingDeveloper** [comment]
I can be wrong but with current decode routine some codes get skipped anyway. If you want catch all codes, you must improve that part where you combine two messages you get via Bluetooth and then trying decode it. 
Or dig mapping files from .apk and then decode routines get improved  and status codes could get imported just by decompiling .apk. This way even if new mappings gets added to .apk all you need just decompile from time to time.

**Comment by TechHummel** [comment]
> Have you used some kind of formatter in this change? Can run it in the GitHub action to verify that the files are properly formatted?

Yes, I ran isort as I changed imports. I also forgot that my VSCode automatically formats Python files with black (also used by Homeassistant themselves). Should I change my commit or would you rather me add a check via GitHub actions and we switch to black?

**Comment by StarvingDeveloper** [comment]
IDK where to discus this, but looks like sub-state get decoded wrong - awhile ago when saw my washer doing nothing and catched substate code 0 I was sure it was IDLE.
But today I can see: prewash, idle, washing, rinsing. I know that "idle" part was steam to remove dirt, and last time I seen same IDLE code 0 definitely wasn't steam program.

**Comment by rowysock** [comment]
@TechHummel `This branch cannot be rebased due to conflicts`

@StarvingDeveloper 3 lines can happen only as a result of a skipped message like 
* line 1
* line 1
* line 2
I'm pretty sure this is how it works in the original app and is the same for all of the appliances.

For your appliance, it may be that something is not decoded properly. Please create an issue to support your specific appliance. Please specify all you can like model, number you enter in the original app, logs if you can

**Comment by rowysock** [comment]
@TechHummel It would be fantastic to have black run as a GitHub action. This can be done in a separate PR

**Comment by TechHummel** [comment]
> @TechHummel It would be fantastic to have black run as a GitHub action. This can be done in a separate PR
Will work on this once the other PR is merged (since actions are introduced there).

I rebased locally and force-pushed - does this work now 🤔

**Comment by rowysock** [comment]
the part "x01" probably means it's not part of a regular message, but some technical stuff. Does it happen with every message, or only after connecting?

**Comment by StarvingDeveloper** [comment]
> the part "x01" probably means it's not part of a regular message, but some technical stuff. Does it happen with every message, or only after connecting?

Depend from the washing/drying program.

**Pull request merged**
