### PR TITLE
Handle advanced AC features

### LINKED ISSUE #71: Support for advanced AC features
Add support for:
* AIR_CONDITIONER_MODE_DEHUMIDIFICATION
* AIR_CONDITIONER_JET_MODE
* AIR_CONDITIONER_SOFT_AIR
* AIR_CONDITIONER_UP_DOWN_VANE_CONTROL
* AIR_CONDITIONER_LEFT_RIGHT_VANE_CONTROL
* AIR_CONDITIONER_SLEEP_MODE
* AIR_CONDITIONER_AUTO_SWITCH_ON
* AIR_CONDITIONER_AUTO_SWITCH_OFF
* AIR_CONDITIONER_INSTANT_CONSUMPTION

### PR DESCRIPTION
**Pull request by rowysock**
Closes #71

### CODE REVIEW

**Comment by rowysock** [comment]
When the user changes SWING_MODE, and VANE_CONTROL for an axis has to be enabled I'm choosing the AUTO mode always. This is different than you described in https://github.com/rowysock/home-assistant-HomeWhiz/issues/71#issuecomment-1369228482 but simpler

**Comment by rowysock** [comment]
@TechHummel just a friendly reminder :)

**Review by TechHummel — APPROVED** [review]
Nice work!

**Comment by rowysock** [comment]
> Nice work!

Thank you!

**Pull request merged**
