### PR TITLE
Add remote entities as sensor entities too 

### LINKED ISSUE #37: Change entity class of "State" and "Sub state" to enum
In the recent changes, Home Assistant introduced a new entity class: "enum". This class can specify all of the available options to be used in automation.
We should use this class for "State" and "Sub state" when this feature is available in the stable release

https://github.com/home-assistant/core/pull/82489
https://developers.home-assistant.io/docs/core/entity/sensor/#:~:text=system%20is%20metric.-,options,-list

### LINKED ISSUE #84: Duplicate the select entities as sensor entities
> When adding `state` from the `select` to my dashboard, it pulls it in as a dropdown (which is obviously default behaviour). However, there doesn't seem to be a clear-cut way to have it render `state` as text in the same manner as a sensor...
> 
> ...unless I'm missing something blatantly obvious.

_Originally posted by @TheKamakaZi in https://github.com/rowysock/home-assistant-HomeWhiz/issues/79#issuecomment-1366866977_

### PR DESCRIPTION
**Pull request by TechHummel**
Closes #37, closes #84

### CODE REVIEW

**Comment by TechHummel** [comment]
Sadly, translations of the sensor options are not working for me! 😢

**Review by rowysock — APPROVED** [review]
Nice! Does it close #84 ?

**Comment by TechHummel** [comment]
Yes, that's the idea! 😄
I tried copying the contents of the select translation to the sensor translation but no success yet 😞
I'm not sure if I ever verified that the sensor translations are working, did you?

**Comment by TechHummel** [comment]
Managed to get translations working!
image

Current device class of the sensor entities is enum
image
whereas it is homewhiz specific for the select entities.
image

@rowysock Do we want to have specific classes for each entity again? Else, all translations would need to be moved (state, enum key). I think I do prefer this - translations will be less organized but we'll stick to stock classes.
image

I also noticed that the current translations for the sensor do not work for exactly this reason (sub_state sensor is enum class, not homewhiz__SUB_STATE).

If you agree, I will rearrange translations and this MR would be ready 👍

**Pull request merged**
